import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  titlePage: {
    padding: 20,
    fontFamily: 'Helvetica',
  },
  titleBorder: {
    border: '1.5pt solid #1080C2',
    borderRadius: 8,
    width: '100%',
    height: '100%',
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  companyName: {
    fontSize: 11,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  objectInfo: {
    fontSize: 14,
    textAlign: 'center',
  },
  mainTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  yearInfo: {
    fontSize: 10,
    textAlign: 'center',
  },
  page: {
    padding: 15,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  pageBorder: {
    position: 'absolute',
    top: 15,
    left: 15,
    right: 15,
    bottom: 15,
    border: '1.5pt solid #1080C2',
    borderRadius: 8,
  },
  pageContent: {
    padding: 15,
  },
  pageTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1080C2',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 3,
  },
  pageSubtitle: {
    fontSize: 10,
    color: '#888888',
    textAlign: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: 6,
    marginLeft: 10,
    marginRight: 10,
  },
  section: {
    marginBottom: 5,
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E8E8E8',
    paddingTop: 3,
    paddingBottom: 2,
    marginLeft: 10,
    marginRight: 10,
    justifyContent: 'space-between',
  },
  labelFix: {
    fontSize: 9,
    flexWrap: 'wrap',
  },
  value: {
    fontSize: 9,
    color: '#1080C2',
    fontWeight: 'bold',
  },
  note: {
    fontSize: 7,
    color: '#777777',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 2,
    marginBottom: 4,
    fontFamily: 'NotoSansMath',
  },
  card: {
    marginTop: 8,
    marginBottom: 6,
    marginLeft: 10,
    marginRight: 10,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1.5,
  },
  cardText: {
    fontSize: 9,
    lineHeight: 1.3,
  },
  cardTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  successText: {
    color: '#00A064',
  },
  errorText: {
    color: '#DC3232',
  },
  conclusion: {
    marginTop: 15,
    padding: 10,
    backgroundColor: '#F0F8FF',
    borderRadius: 8,
    alignItems: 'center',
  },
  conclusionText: {
    fontSize: 10,
    fontWeight: 'semibold',
    marginBottom: 5,
    textAlign: 'center',
  },
  conclusionResult: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    alignItems: 'center',
  },
  table: {
    display: 'table',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRightWidth: 0,
    borderBottomWidth: 0,
    margin: 10,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#E8F4FC',
    padding: 5,
    fontWeight: 'bold',
    fontSize: 8,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E8E8E8',
    padding: 5,
    fontSize: 8,
  },
  tableCell: {
    flex: 1,
    textAlign: 'center',
    fontWeight: 'normal',
  },
  mathText: {
    fontSize: 9,
    color: '#1080C2',
    fontWeight: 'bold',
    fontFamily: 'NotoSansMath',
    lineHeight: 1.25,
  },
  mainVariableText: {
    fontSize: 9,
    color: '#1080C2',
    fontWeight: 'bold',
  },
  unicodeText: {
    fontFamily: 'NotoSansMath',
  },
  labelWithSubscript: {
    flexDirection: "row",
    alignItems: 'baseline',
    maxWidth: '85%',
    marginRight: 2,
    flex: 1,
    justifyContent: "flex-start",
  },

  subscriptText: {
    fontSize: 6,
    lineHeight: 1,
    color: '#1080C2',
    fontWeight: 'bold',
  },
});
